export const POKEMON_ACTION_TYPES = {
    SET_IS_POKEMON_CATCHED: 'pokemon/SET_IS_POKEMON_CATCHED',
    FETCH_POKEMON_START: 'pokemon/FETCH_POKEMON_START',
    FETCH_POKEMON_SUCCESS: 'pokemon/FETCH_POKEMON_SUCCESS',
    FETCH_POKEMON_FAILED: 'pokemon/FETCH_POKEMON_FAILED',
  };