export const OBTENER_POKEMONES_EXITO = 'OBTENER_POKEMONES_EXITO'
export const SIGUIENTE_POKEMONES_EXITO = 'SIGUIENTE_POKEMONES_EXITO'
export const ANTERIOR_POKEMONES_EXITO = 'ANTERIOR_POKEMONES_EXITO'